/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CgsRouteImport } from './routes/cgs'
import { Route as ContactSalesRouteImport } from './routes/contact-sales'
import { Route as ErentRouteImport } from './routes/erent'
import { Route as OapamRouteImport } from './routes/oapam'
import { Route as PosEbyteRouteImport } from './routes/pos-ebyte'
import { Route as SmartMenuNfcRouteImport } from './routes/smart-menu-nfc'
import { Route as WhoRouteImport } from './routes/who'
import { Route as ServicesDesktopRouteImport } from './routes/services/desktop'
import { Route as ServicesMobileRouteImport } from './routes/services/mobile'
import { Route as ServicesWebRouteImport } from './routes/services/web'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CgsRoute = CgsRouteImport.update({
  id: '/cgs',
  path: '/cgs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactSalesRoute = ContactSalesRouteImport.update({
  id: '/contact-sales',
  path: '/contact-sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ErentRoute = ErentRouteImport.update({
  id: '/erent',
  path: '/erent',
  getParentRoute: () => rootRouteImport,
} as any)
const OapamRoute = OapamRouteImport.update({
  id: '/oapam',
  path: '/oapam',
  getParentRoute: () => rootRouteImport,
} as any)
const PosEbyteRoute = PosEbyteRouteImport.update({
  id: '/pos-ebyte',
  path: '/pos-ebyte',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartMenuNfcRoute = SmartMenuNfcRouteImport.update({
  id: '/smart-menu-nfc',
  path: '/smart-menu-nfc',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoRoute = WhoRouteImport.update({
  id: '/who',
  path: '/who',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDesktopRoute = ServicesDesktopRouteImport.update({
  id: '/services/desktop',
  path: '/services/desktop',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMobileRoute = ServicesMobileRouteImport.update({
  id: '/services/mobile',
  path: '/services/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebRoute = ServicesWebRouteImport.update({
  id: '/services/web',
  path: '/services/web',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cgs': typeof CgsRoute
  '/contact-sales': typeof ContactSalesRoute
  '/erent': typeof ErentRoute
  '/oapam': typeof OapamRoute
  '/pos-ebyte': typeof PosEbyteRoute
  '/smart-menu-nfc': typeof SmartMenuNfcRoute
  '/who': typeof WhoRoute
  '/services/desktop': typeof ServicesDesktopRoute
  '/services/mobile': typeof ServicesMobileRoute
  '/services/web': typeof ServicesWebRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cgs': typeof CgsRoute
  '/contact-sales': typeof ContactSalesRoute
  '/erent': typeof ErentRoute
  '/oapam': typeof OapamRoute
  '/pos-ebyte': typeof PosEbyteRoute
  '/smart-menu-nfc': typeof SmartMenuNfcRoute
  '/who': typeof WhoRoute
  '/services/desktop': typeof ServicesDesktopRoute
  '/services/mobile': typeof ServicesMobileRoute
  '/services/web': typeof ServicesWebRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cgs': typeof CgsRoute
  '/contact-sales': typeof ContactSalesRoute
  '/erent': typeof ErentRoute
  '/oapam': typeof OapamRoute
  '/pos-ebyte': typeof PosEbyteRoute
  '/smart-menu-nfc': typeof SmartMenuNfcRoute
  '/who': typeof WhoRoute
  '/services/desktop': typeof ServicesDesktopRoute
  '/services/mobile': typeof ServicesMobileRoute
  '/services/web': typeof ServicesWebRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cgs'
    | '/contact-sales'
    | '/erent'
    | '/oapam'
    | '/pos-ebyte'
    | '/smart-menu-nfc'
    | '/who'
    | '/services/desktop'
    | '/services/mobile'
    | '/services/web'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cgs'
    | '/contact-sales'
    | '/erent'
    | '/oapam'
    | '/pos-ebyte'
    | '/smart-menu-nfc'
    | '/who'
    | '/services/desktop'
    | '/services/mobile'
    | '/services/web'
  id:
    | '__root__'
    | '/'
    | '/cgs'
    | '/contact-sales'
    | '/erent'
    | '/oapam'
    | '/pos-ebyte'
    | '/smart-menu-nfc'
    | '/who'
    | '/services/desktop'
    | '/services/mobile'
    | '/services/web'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CgsRoute: typeof CgsRoute
  ContactSalesRoute: typeof ContactSalesRoute
  ErentRoute: typeof ErentRoute
  OapamRoute: typeof OapamRoute
  PosEbyteRoute: typeof PosEbyteRoute
  SmartMenuNfcRoute: typeof SmartMenuNfcRoute
  WhoRoute: typeof WhoRoute
  ServicesDesktopRoute: typeof ServicesDesktopRoute
  ServicesMobileRoute: typeof ServicesMobileRoute
  ServicesWebRoute: typeof ServicesWebRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgs': {
      id: '/cgs'
      path: '/cgs'
      fullPath: '/cgs'
      preLoaderRoute: typeof CgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-sales': {
      id: '/contact-sales'
      path: '/contact-sales'
      fullPath: '/contact-sales'
      preLoaderRoute: typeof ContactSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erent': {
      id: '/erent'
      path: '/erent'
      fullPath: '/erent'
      preLoaderRoute: typeof ErentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oapam': {
      id: '/oapam'
      path: '/oapam'
      fullPath: '/oapam'
      preLoaderRoute: typeof OapamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos-ebyte': {
      id: '/pos-ebyte'
      path: '/pos-ebyte'
      fullPath: '/pos-ebyte'
      preLoaderRoute: typeof PosEbyteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-menu-nfc': {
      id: '/smart-menu-nfc'
      path: '/smart-menu-nfc'
      fullPath: '/smart-menu-nfc'
      preLoaderRoute: typeof SmartMenuNfcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who': {
      id: '/who'
      path: '/who'
      fullPath: '/who'
      preLoaderRoute: typeof WhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/desktop': {
      id: '/services/desktop'
      path: '/services/desktop'
      fullPath: '/services/desktop'
      preLoaderRoute: typeof ServicesDesktopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/mobile': {
      id: '/services/mobile'
      path: '/services/mobile'
      fullPath: '/services/mobile'
      preLoaderRoute: typeof ServicesMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web': {
      id: '/services/web'
      path: '/services/web'
      fullPath: '/services/web'
      preLoaderRoute: typeof ServicesWebRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CgsRoute: CgsRoute,
  ContactSalesRoute: ContactSalesRoute,
  ErentRoute: ErentRoute,
  OapamRoute: OapamRoute,
  PosEbyteRoute: PosEbyteRoute,
  SmartMenuNfcRoute: SmartMenuNfcRoute,
  WhoRoute: WhoRoute,
  ServicesDesktopRoute: ServicesDesktopRoute,
  ServicesMobileRoute: ServicesMobileRoute,
  ServicesWebRoute: ServicesWebRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
